name: project-cis552
version: 0.1.0.0
github: "githubuser/project-cis552"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2020 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/project-cis552#readme>

# You can add any libraries from stackage here (https://www.stackage.org/lts-18.8).
# if you need a library that is not available on stackage, you will need to add
# an entry in stack.yaml.
dependencies:
  - base >= 4.14
  - HUnit >= 1.6
  - QuickCheck >= 2.14.2
  - containers == 0.6.2.1
  - mtl
  - gloss
  - JuicyPixels
  - vector
  - ieee754

library:
  source-dirs:
    - src
    - src/img
    - src/nbody

  default-extensions:
    - ScopedTypeVariables
    - TypeApplications
    - InstanceSigs
    - KindSignatures
    - LambdaCase
    - DeriveFunctor
    - DeriveFoldable
    - DeriveTraversable
    - GeneralizedNewtypeDeriving
    - TupleSections
    - MultiParamTypeClasses
    - FlexibleInstances
    - FlexibleContexts
    - UndecidableInstances
    - NoMonomorphismRestriction
    - NoStarIsType

executables:
  project-cis552-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - project-cis552
    default-extensions:
      - ScopedTypeVariables
      - TypeApplications
      - InstanceSigs
      - KindSignatures
      - LambdaCase
      - DeriveFunctor
      - DeriveFoldable
      - DeriveTraversable
      - GeneralizedNewtypeDeriving
      - TupleSections
      - MultiParamTypeClasses
      - FlexibleInstances
      - FlexibleContexts
      - UndecidableInstances
      - NoMonomorphismRestriction
      - NoStarIsType

tests:
  project-cis552-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - project-cis552
    default-extensions:
      - ScopedTypeVariables
      - TypeApplications
      - InstanceSigs
      - KindSignatures
      - LambdaCase
      - DeriveFunctor
      - DeriveFoldable
      - DeriveTraversable
      - GeneralizedNewtypeDeriving
      - TupleSections
      - MultiParamTypeClasses
      - FlexibleInstances
      - FlexibleContexts
      - UndecidableInstances
      - NoMonomorphismRestriction
      - NoStarIsType
